In [55]:
import pandas as pd

In [59]:
df = pd.read_csv('/Users/James/Desktop/For_Hire_Vehicles__FHV__-_Active_Drivers.csv')
df.T

,0,1,2,3,4,5,6,7,8,9,...,188921,188922,188923,188924,188925,188926,188927,188928,188929,188930
License Number,493092,681774,498143,686178,664245,498190,689626,695067,501583,694478,...,5611960,5612047,5614015,5614355,5615133,5617432,5618248,5619148,5619263,5624799
Name,"MAIGA,BOUNAFOU","GNANARAJ,SINNA","KAREEM,LUKMAN,ABDUL","TAVERAS,OLGA","CORNIEL,PEDRO,A","JAMILU,MOHAMMED,Y","BRODIE,ALFRED,A,JR","ORTIZ,ANGEL1","CSONKA,ATTILA,I","MAHMOUD,ASHRAF",...,"DAVIS,GREGORY,PAUL","BHUIYAN,MOHAMMAD,H,R","ANJUM,ZAID","LEEPUTRA,STEVANUS,B","HUNG,JACOB,K","MESIHA,SHADY,ADEL","ROUF,ARMAN","BAKHTARI,HADI","BASWAL,VIJANDER,KUMAR","VOULGARIS,GEORGE"
Type,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,...,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER,FOR HIRE VEHICLE DRIVER
Expiration Date,11/24/2019,04/03/2020,01/03/2021,08/21/2019,04/10/2022,02/19/2020,11/14/2019,04/19/2019,08/02/2020,01/31/2020,...,06/04/2019,05/28/2019,06/09/2019,05/20/2019,06/17/2019,06/08/2019,06/09/2019,06/12/2019,06/17/2019,07/08/2019
Wheelchair Accessible Trained,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV,...,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV,WAV
Last Date Updated,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,...,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019,04/15/2019
Last Time Updated,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25,...,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25,13:25

In [39]:
df.shape

(188931, 7)

In [7]:
# df = df['Name'].sort_values()

In [9]:
# df.to_frame()

                                  Name
107335                  A  JEAN,VERLEN
61460                       A HANNAN,M
174913  A S MOHAMED JAWARD,AYAZ AHAMED
46939                AABIZZA,NOURDDINE
44504                AAFFOUTE,RADOUANE
52584                  AAFOUALLAH,ZIAD
168574                      AAKASH,FNU
40250                   AALAMI,MOHCINE
89973               AALIKAMALUDEEN,A,N
91733                   AALLALOU,SIMON
188907                      AAMAR,ADIL
69190                       AAMAR,ADIL
114690                   AAMAR,ZEESHAN
182311                   AAMER,ZOUHAIR
53374                   AAMIR,MUHAMMAD
85485                 AANOUZ,ABDELHADI
153343                  AANOUZ,MOHAMED
100376                    AAOUINE,SAID
61483                    AARICH,HICHAM
158269               AARNDELL,KAREEM,D
171801                   AARON,DARRELL
133038                 AASHAR,MUHAMMAD
138701           AASHIQ,SHIPU,MOHAMMED
1289                   AASHOUR,IBRAHIM
47228               AASI,TANVEER,AHMED
119810                 AASMI,ABDUL,ELA
102737              AAZAROU,ABDELHAKIM
83310                AAZEM,AHMAD,NAJIM
89086                 AAZEM,MOHAMMAD,N
41472                     ABABIO,KWASI
...                                ...
170482              ZURITA,ALEXANDRA,P
8647                   ZURITA,CARLOS,H
51819                  ZURITA,FABIAN,T
69118                    ZURITA,GALO,F
51820                   ZURITA,NANCY,E
106572                   ZURITA,SAMUEL
41878              ZURITA,XAVIER,JASON
91128                  ZURLNICK,ROBERT
96495                     ZUSIN,SERGEY
122149               ZUSMAN,ALEKSANDER
21899                  ZUYEV,VALERIY,V
2909                ZVAGELSKIY,MIKHAIL
182123            ZVAGOLSKY,KONSTANTIN
36069             ZVENIGORODSKIY,VADIM
4378                   ZVEZDIN,DMITRIY
104925                        ZVI,ELAN
110709                        ZVI,ZION
142854              ZVIRKOVSKYI,SERHII
115963                   ZVONAROV,IVAN
35033                  ZVULUNI,YONATAN
15386             ZWEIGHT,HANZ,NICOLAS
6823                      ZYCH,MARIUSZ
24822                ZYGIEL,ZENON,ADAM
143487                     ZYKO,THOMAS
107920                     ZYKOV,IURII
68265                   ZZAMAN,AKTHERU
150051                   ZZAMAN,KAMRUS
113826               ZZAMAN,MD,AKHTARU
112128               ZZAMAN,MOHAMMAD,M
23084              ZZAMAN,MOLLA,MONIRU

[188931 rows x 1 columns]

In [26]:
# dv = df.groupby(df['Wheelchair Accessible Trained'])
# dv.head()

,License Number,Name,Type,Expiration Date,Wheelchair Accessible Trained,Last Date Updated,Last Time Updated
0,493092,"MAIGA,BOUNAFOU",FOR HIRE VEHICLE DRIVER,11/24/2019,WAV,04/15/2019,13:25
1,681774,"GNANARAJ,SINNA",FOR HIRE VEHICLE DRIVER,04/03/2020,WAV,04/15/2019,13:25
2,498143,"KAREEM,LUKMAN,ABDUL",FOR HIRE VEHICLE DRIVER,01/03/2021,WAV,04/15/2019,13:25
792,502684,"BARIKDAR,PAUL",FOR HIRE VEHICLE DRIVER,11/06/2019,NaN,04/15/2019,13:25
1239,669860,"GUANTE,FACUNDO",FOR HIRE VEHICLE DRIVER,08/31/2019,NaN,04/15/2019,13:25
3302,504529,"ALAM,ASHRAFUL",FOR HIRE VEHICLE DRIVER,06/22/2019,NaN,04/15/2019,13:25

In [68]:
df['Wheelchair Accessible Trained'].replace(df['Wheelchair Accessible Trained'],{'WAV': 1, 'NaN': 0})
df.head()

,License Number,Name,Type,Expiration Date,Wheelchair Accessible Trained,Last Date Updated,Last Time Updated
0,493092,"MAIGA,BOUNAFOU",FOR HIRE VEHICLE DRIVER,11/24/2019,WAV,04/15/2019,13:25
1,681774,"GNANARAJ,SINNA",FOR HIRE VEHICLE DRIVER,04/03/2020,WAV,04/15/2019,13:25
2,498143,"KAREEM,LUKMAN,ABDUL",FOR HIRE VEHICLE DRIVER,01/03/2021,WAV,04/15/2019,13:25
3,686178,"TAVERAS,OLGA",FOR HIRE VEHICLE DRIVER,08/21/2019,WAV,04/15/2019,13:25
4,664245,"CORNIEL,PEDRO,A",FOR HIRE VEHICLE DRIVER,04/10/2022,WAV,04/15/2019,13:25

In [70]:
df['Wheelchair Accessible Trained'].nunique()

1

In [71]:
df['Wheelchair Accessible Trained'].value_counts()

WAV    188849
Name: Wheelchair Accessible Trained, dtype: int64

In [72]:
df.shape

(188931, 7)

In [75]:
print(188931-188849)#non wheelchair accessible vehicle

82