<a href="https://colab.research.google.com/github/will-cotton4/DS-Unit-1-Sprint-5-Data-Storytelling-Blog-Post/blob/master/Project_Week_Test_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
country_names = ["Afghanistan", "Albania", "Algeria", "American Samoa", 
                 "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", 
                 "Argentina", "Armenia", "Aruba", "Australia", "Austria", 
                 "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", 
                 "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", 
                 "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", 
                 "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", 
                 "Canada", "Cape Verde", "Cayman Islands", 
                 "Central African Republic", "Chad", "Chile", "China", 
                 "Christmas Island", "Cocos (Keeling) Islands", "Colombia",
                 "Comoros", "Congo", "Congo, the Democratic Republic of the", 
                 "Cook Islands", "Costa Rica", "Cote d'Ivoire", 
                 "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", 
                 "Denmark", "Djibouti", "Dominica", "Dominican Republic", 
                 "East Timor", "Ecuador", "Egypt", "El Salvador", 
                 "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", 
                 "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji",
                 "Finland", "France", "France Metropolitan", "French Guiana",
                 "French Polynesia", "French Southern Territories", "Gabon", 
                 "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
                 "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", 
                 "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", 
                 "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", 
                 "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", 
                 "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", 
                 "Kiribati", "Korea, Democratic People's Republic of", 
                 "Korea, Republic of", "Kuwait", "Kyrgyzstan", 
                 "Lao, People's Democratic Republic", "Latvia", "Lebanon", 
                 "Lesotho", "Liberia", "Libyan Arab Jamahiriya", 
                 "Liechtenstein", "Lithuania", "Luxembourg", "Macau", 
                 "Macedonia, The Former Yugoslav Republic of", "Madagascar",
                 "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
                 "Marshall Islands", "Martinique", "Mauritania", "Mauritius",
                 "Mayotte", "Mexico", "Micronesia, Federated States of", 
                 "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat",
                 "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", 
                 "Nepal", "Netherlands", "Netherlands Antilles", 
                 "New Caledonia", "New Zealand", "Nicaragua", "Niger", 
                 "Nigeria", "Niue", "Norfolk Island", 
                 "Northern Mariana Islands", "Norway", "Oman", "Pakistan", 
                 "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru",
                 "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico",
                 "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda",
                 "Saint Kitts and Nevis", "Saint Lucia", 
                 "Saint Vincent and the Grenadines", "Samoa", "San Marino",
                 "Sao Tome and Principe", "Saudi Arabia", "Senegal",
                 "Seychelles", "Sierra Leone", "Singapore", 
                 "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", 
                 "Somalia", "South Africa", 
                 "South Georgia and the South Sandwich Islands", "Spain", 
                 "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", 
                 "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", 
                 "Sweden", "Switzerland", "Syrian Arab Republic", 
                 "Taiwan, Province of China", "Tajikistan", 
                 "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau",
                 "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", 
                 "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda",
                 "Ukraine", "United Arab Emirates", "United Kingdom", 
                 "United States", "United States Minor Outlying Islands", 
                 "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam",
                 "Virgin Islands (British)", "Virgin Islands (U.S.)",
                 "Wallis and Futuna Islands", "Western Sahara", "Yemen",
                 "Yugoslavia", "Zambia", "Zimbabwe"]

#### Store country names in list:

In [0]:
country_names = ["Afghanistan", "Albania", "Algeria", "American Samoa", 
                 "Andorra", "Angola", "Anguilla", "Antigua and Barbuda", 
                 "Argentina", "Armenia", "Aruba", "Australia", "Austria", 
                 "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", 
                 "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", 
                 "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", 
                 "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", 
                 "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", 
                 "Canada", "Cape Verde", "Cayman Islands", 
                 "Central African Republic", "Chad", "Chile", "China", 
                 "Christmas Island", "Cocos (Keeling) Islands", "Colombia",
                 "Comoros", "Congo", "Congo, the Democratic Republic of the", 
                 "Cook Islands", "Costa Rica", "Cote d'Ivoire", 
                 "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", 
                 "Denmark", "Djibouti", "Dominica", "Dominican Republic", 
                 "East Timor", "Ecuador", "Egypt", "El Salvador", 
                 "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", 
                 "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji",
                 "Finland", "France", "France Metropolitan", "French Guiana",
                 "French Polynesia", "French Southern Territories", "Gabon", 
                 "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
                 "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", 
                 "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", 
                 "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", 
                 "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", 
                 "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", 
                 "Kiribati", "Korea, Democratic People's Republic of", 
                 "Korea, Republic of", "Kuwait", "Kyrgyzstan", 
                 "Lao, People's Democratic Republic", "Latvia", "Lebanon", 
                 "Lesotho", "Liberia", "Libyan Arab Jamahiriya", 
                 "Liechtenstein", "Lithuania", "Luxembourg", "Macau", 
                 "Macedonia, The Former Yugoslav Republic of", "Madagascar",
                 "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
                 "Marshall Islands", "Martinique", "Mauritania", "Mauritius",
                 "Mayotte", "Mexico", "Micronesia, Federated States of", 
                 "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat",
                 "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", 
                 "Nepal", "Netherlands", "Netherlands Antilles", 
                 "New Caledonia", "New Zealand", "Nicaragua", "Niger", 
                 "Nigeria", "Niue", "Norfolk Island", 
                 "Northern Mariana Islands", "Norway", "Oman", "Pakistan", 
                 "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru",
                 "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico",
                 "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda",
                 "Saint Kitts and Nevis", "Saint Lucia", 
                 "Saint Vincent and the Grenadines", "Samoa", "San Marino",
                 "Sao Tome and Principe", "Saudi Arabia", "Senegal",
                 "Seychelles", "Sierra Leone", "Singapore", 
                 "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", 
                 "Somalia", "South Africa", 
                 "South Georgia and the South Sandwich Islands", "Spain", 
                 "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", 
                 "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", 
                 "Sweden", "Switzerland", "Syrian Arab Republic", 
                 "Taiwan, Province of China", "Tajikistan", 
                 "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau",
                 "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", 
                 "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda",
                 "Ukraine", "United Arab Emirates", "United Kingdom", 
                 "United States", "United States Minor Outlying Islands", 
                 "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam",
                 "Virgin Islands (British)", "Virgin Islands (U.S.)",
                 "Wallis and Futuna Islands", "Western Sahara", "Yemen",
                 "Yugoslavia", "Zambia", "Zimbabwe"]

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

updated_wdi_url = 'https://raw.githubusercontent.com/will-cotton4/DS-Unit-1-Sprint-5-Data-Storytelling-Blog-Post/master/Updated%20WDI%20Data.csv'

wdi = pd.read_csv(updated_wdi_url).drop(columns = ['Series Code', 'Country Code'])

short_years = {'2009 [YR2009]': 2009, '2010 [YR2010]': 2010, '2011 [YR2011]': 2011, '2012 [YR2012]': 2012,
       '2013 [YR2013]': 2013, '2014 [YR2014]': 2014, '2015 [YR2015]': 2015, '2016 [YR2016]': 2016,
       '2017 [YR2017]': 2017, '2018 [YR2018]': 2018, '1999 [YR1999]': 1999, '2000 [YR2000]': 2000,
       '2001 [YR2001]': 2001, '2002 [YR2002]': 2002, '2003 [YR2003]': 2003, '2008 [YR2008]': 2008,
       '2007 [YR2007]': 2007, '2006 [YR2006]': 2006, '2005 [YR2005]': 2005, '2004 [YR2004]': 2004}
wdi = wdi.rename(columns = short_years)

short_names = {"GNI per capita, PPP (current international $)":"GNI per capita",
              "Human capital index (HCI) (scale 0-1)": "HCI",
              "Foreign direct investment, net inflows (BoP, current US$)": "FDI",
              "Agriculture, forestry, and fishing, value added (% of GDP)": "Agriculture pct of GDP",
              "Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)": "Poverty (1.90)",
              "Domestic credit provided by financial sector (% of GDP)": "Domestic credit pct of GDP",
              "Poverty headcount ratio at national poverty lines (% of population)": "Poverty (natl lines)"}
wdi = wdi.replace(short_names)
wdi = wdi.replace("..",np.NaN)

# All of the data for 2018 is missing:
wdi = wdi.drop(columns=[2018])
for column in range(1999, 2018):
  wdi[column] = pd.to_numeric(wdi[column])

**Here we'll clean up and separate the data so we can see which countries have enough informaton to be analyzed.**

In [23]:
print(wdi['Country Name'].values)

['Argentina' 'Argentina' 'Argentina' ... nan
 'Data from database: World Development Indicators'
 'Last Updated: 03/21/2019']

In [20]:
dom_credit = wdi[wdi['Series Name'] == "Domestic credit pct of GDP"].drop(
    columns=['Series Name'])
dom_credit

,Country Name,2009,2010,2011,2012,2013,2014,2015,2016,2017,1999,2000,2001,2002,2003,2008,2007,2006,2005,2004
2,Argentina,25.663791,25.332319,26.465961,30.601222,33.187392,34.432140,40.427628,38.114808,39.252751,35.504424,34.451692,37.243364,62.421086,50.627821,21.961534,25.832515,28.168600,34.940798,41.894911
13,Australia,151.012279,154.042992,151.418032,150.157939,155.533074,164.710900,175.977102,182.772402,NaN,91.383143,93.403105,92.311100,99.219033,103.820875,159.631477,146.602616,118.352640,113.444892,108.217423
24,Brazil,90.474952,93.388703,95.155447,101.064049,100.045939,103.440537,107.063169,111.327117,111.260738,69.403668,70.681245,72.865149,75.181667,74.262185,85.908778,87.315332,82.910090,76.235192,72.908775
35,China,141.680511,142.198771,140.603051,149.082586,155.735526,167.236891,193.409580,215.182681,215.237744,118.162356,118.400434,121.659923,141.824172,150.109580,118.735590,125.691588,131.580294,132.590516,138.667132
46,France,140.570031,143.848134,145.879140,147.673693,143.813566,146.773578,147.414475,155.200425,157.671515,NaN,NaN,102.780978,100.525182,102.605929,143.239041,137.582004,127.018409,106.060009,103.096738
57,Germany,128.450989,164.797563,161.966764,156.924945,136.886322,139.753962,134.343108,133.762345,128.586483,NaN,NaN,139.566759,138.099752,137.079745,122.282823,120.480139,127.361705,132.598376,134.166175
68,India,72.344835,74.256754,76.145910,77.179475,77.916848,75.908170,75.654111,75.033802,73.459810,48.991970,52.788825,54.523291,58.740486,57.425177,69.791684,62.713102,62.779901,60.188124,59.385764
79,Indonesia,36.966387,34.182439,36.550140,40.768033,43.429264,43.423845,46.774066,47.936171,46.967490,62.073959,60.676834,54.467203,52.393321,49.204177,36.770193,40.580211,41.659359,46.204917,49.623233
90,Italy,146.288940,160.457821,164.120482,177.391625,172.714481,172.109026,169.675067,170.643877,166.163978,NaN,NaN,93.945200,93.531983,99.246960,137.613265,124.819919,108.617881,104.719695,100.327977
101,Japan,317.013060,315.499050,324.526906,331.624977,340.275085,347.483615,343.234462,346.645661,NaN,296.784077,294.996810,285.169503,293.152265,302.108672,289.946549,282.066689,290.107704,296.117988,298.362903
112,"Korea, Rep.",157.350573,151.040821,153.165400,155.845025,155.803323,162.294360,165.957140,169.630377,170.056468,66.250237,70.939739,128.066159,134.158901,128.437367,158.745496,143.579245,138.512616,125.451758,121.432124
123,Mexico,42.902039,43.644843,44.094243,45.634803,48.472481,49.051298,52.536235,54.746260,55.172660,29.076924,28.006562,27.252101,30.660287,31.892575,36.724825,36.617821,34.043445,31.008723,30.867549
134,Netherlands,207.231920,218.267586,223.979862,234.173481,209.348937,218.244576,206.369530,208.854308,191.911267,NaN,NaN,138.487632,144.016635,150.803184,182.292310,184.207540,165.740523,166.212434,159.127685
145,Russian Federation,34.122260,37.721335,36.752930,38.993524,44.075596,47.222678,56.710148,58.252624,58.852958,NaN,24.926084,25.731249,26.856562,27.875037,24.416350,23.916977,21.530842,20.814201,25.657198
156,Saudi Arabia,0.523787,-0.124729,-4.102054,-10.151829,-7.861553,1.765158,20.500687,34.059454,38.886665,40.862851,34.541125,39.118136,40.715406,43.063621,-3.652808,16.103113,21.304035,28.824060,40.351420
167,Spain,233.833865,240.990624,248.931149,245.570318,223.604139,211.247808,193.838044,187.450582,178.515067,NaN,NaN,116.419357,119.993647,128.282255,223.154113,199.817544,178.960072,155.568009,136.734113
178,Switzerland,175.501012,172.771047,174.814726,182.295550,172.656007,173.965855,174.924292,179.710041,NaN,165.307658,157.956691,153.876637,154.716892,158.448857,165.000848,167.243816,164.865594,161.321463,159.740608
189,Turkey,61.680359,68.046357,66.650897,67.143890,72.903887,75.322745,77.542290,80.604172,80.842812,35.876063,37.016819,51.799205,46.300564,41.564416,52.197425,47.176848,43.977058,43.949950,40.070404
200,United Kingdom,208.895177,206.241230,197.157132,192.182233,179.968385,166.874606,161.131804,165.786623,167.513268,109.844957,116.667325,123.133649,128.310543,132.245937,194.654069,171.554929,155.769679,146.455316,140.711370
211,United States,234.403448,231.430252,231.025933,233.517842,247.462286,250.601310,235.954606,241.891278,NaN,201.263956,190.962275,198.608487,191.805270,206.598919,216.777838,235.909626,226.340052,216.345981,212.935939
222,Afghanistan,4.827675,4.781278,-2.577263,-1.982235,-2.070885,-0.607984,-0.411141,-1.186978,-2.468349,NaN,NaN,NaN,NaN,NaN,4.964943,0.540676,-4.883132,NaN,NaN
233,Albania,68.925499,67.452775,70.308698,70.175972,72.180445,73.179418,68.137859,66.292840,63.496350,53.273544,51.133159,48.737330,48.138323,47.193313,66.511877,62.214473,55.955214,50.548189,47.204069
244,Algeria,-8.953419,-6.626649,-4.514118,-2.111520,3.003544,18.002579,39.970479,54.383172,67.922035,45.819316,28.271131,36.266915,37.802788,31.235128,-12.698268,-3.636038,3.648202,7.337901,21.652207
255,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,Angola,31.336932,18.961168,15.497628,13.947739,17.139388,21.054865,27.391547,27.108776,29.555915,7.219949,-14.755435,-0.319143,4.091321,5.278390,8.984282,1.735302,-3.995773,1.879179,5.616808
288,Antigua and Barbuda,97.162533,99.260706,99.338602,91.756866,90.595303,80.935779,64.946080,62.328816,60.227742,75.946547,76.365909,80.052937,83.457118,82.576768,82.545948,76.389448,74.117509,75.513622,77.310767
299,Armenia,21.529879,27.815698,36.381448,41.388462,43.149714,51.301029,48.259976,54.370777,58.231938,10.749978,11.547501,9.334876,7.378001,5.559478,18.593274,12.134288,8.064048,8.788981,6.684199
310,Aruba,53.214375,59.385581,56.787818,62.907979,64.130902,66.194012,65.706351,69.810511,NaN,44.554334,44.102276,44.825575,49.097468,54.437839,48.114347,51.546080,53.312742,54.165700,51.681223
321,Austria,135.092199,135.058648,132.087438,135.253692,130.425655,125.433770,123.436409,129.822813,125.255785,NaN,NaN,120.610318,118.959838,118.060940,126.300241,122.698602,125.660297,125.979716,118.559547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2576,IDA blend,29.444488,27.409050,28.561574,29.816284,31.153574,30.480368,33.264656,37.587128,36.998599,30.736114,26.109231,26.903726,28.126977,26.328803,26.714625,23.165326,17.928798,22.318537,23.453847
2587,IDA only,27.971232,29.368440,30.386053,30.444580,30.972211,33.085386,35.770706,38.759725,41.088909,24.873176,23.538572,26.959280,26.506825,25.924536,25.692897,25.552302,25.291297,26.358888,25.598038
2598,IDA total,28.709591,28.378242,29.457611,30.116051,31.065983,31.697614,34.479714,38.187157,39.096916,27.495268,24.656261,26.934587,27.252426,26.110472,26.221223,24.354898,21.539885,24.381317,24.574602
2609,Late-demographic dividend,109.438511,109.483760,108.127878,114.371029,119.752696,129.350512,153.610419,168.951379,168.115001,89.194048,82.964643,86.646172,96.046303,99.220825,90.390848,92.577683,90.140766,89.610195,92.676992
2620,Latin America & Caribbean,62.395935,64.877737,67.754335,71.070641,72.174077,74.872367,73.674363,76.805825,78.127131,44.967786,43.981168,43.918708,47.317352,47.988347,56.923549,56.553425,52.886110,49.055465,46.971583
2631,Latin America & Caribbean (excluding high income),63.999190,67.020178,70.520398,73.769722,74.714310,77.574400,76.445722,79.929537,81.414001,45.081867,43.818689,42.603288,43.977112,45.531626,58.322678,57.937392,53.559245,48.460710,45.146566
2642,Latin America & the Caribbean (IDA & IBRD coun...,62.309352,64.845779,67.731959,71.058285,72.158424,74.867094,73.675773,76.812688,78.140366,44.928422,43.928196,43.832997,47.223760,47.886072,56.843084,56.479813,52.790883,48.950816,46.860595
2653,Least developed countries: UN classification,27.365787,27.229629,27.526096,26.712206,28.120965,30.658466,34.481601,37.484175,40.121705,21.633614,19.848624,24.087607,23.425573,22.925088,21.910706,20.327247,19.961947,21.946254,22.623815
2664,Low & middle income,85.337768,86.663444,87.755993,93.220808,98.322664,106.463781,124.294336,135.948760,136.514761,68.553788,65.420619,68.116790,73.539080,76.268378,70.535786,71.390941,70.319288,69.752598,72.117545
2675,Low income,18.909880,19.404590,19.568958,20.060335,21.350958,22.629247,25.631019,26.906454,NaN,23.111034,20.138395,22.554095,25.970333,22.161613,18.339036,19.426472,18.586703,21.295119,19.952857
2686,Lower middle income,57.444578,56.625765,57.753467,58.455077,60.075483,60.549716,63.018941,66.631059,64.355018,49.236094,49.975043,50.233751,51.102149,49.993168,53.662672,50.354273,47.882565,48.724925,49.815708
2697,Middle East & North Africa,49.728724,47.706946,45.951235,43.483455,44.950914,51.672028,69.073740,80.026527,77.084544,57.736067,52.611362,57.558408,57.254739,55.680738,39.305000,43.980138,42.876240,44.735939,49.849982
2708,Middle East & North Africa (excluding high inc...,42.617592,44.333535,47.248112,47.526922,47.741907,56.022118,71.643822,85.795269,NaN,61.876731,60.467401,62.790262,61.753679,58.773086,34.339439,39.522433,41.485561,42.971235,49.459066
2719,Middle East & North Africa (IDA & IBRD countries),42.617592,44.333535,47.248112,47.526922,47.741907,56.022118,71.643822,85.795269,NaN,62.479859,61.018666,63.110264,62.078162,59.069984,34.502021,39.706567,41.693238,43.223460,49.632792
2730,Middle income,86.310036,87.559501,88.669869,94.175916,99.361066,107.506493,125.512831,137.225405,137.518162,69.522373,66.491328,69.117435,74.591361,77.426303,71.354616,72.343408,71.298706,70.715148,73.189644
2741,North America,234.403448,231.430252,231.025933,233.517842,247.462286,250.601310,235.954606,241.891278,NaN,195.578835,185.583718,198.561877,191.837807,205.139542,212.544934,228.004723,225.223873,214.720396,211.059594
2752,Not classified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2763,OECD members,200.592013,203.603939,204.012142,206.560297,204.234379,205.800116,200.891014,207.259722,NaN,190.847676,186.799601,174.336857,170.659688,175.805584,184.379064,184.680769,182.648033,178.089821,176.129563
2774,Other small states,92.517421,85.642934,79.494079,81.296109,78.596033,80.939692,104.111360,114.615348,112.225335,40.557497,35.693020,40.949981,45.006795,47.903338,78.236989,81.423066,75.013399,73.863490,49.893835
2785,Pacific island small states,95.813927,90.801698,79.608059,77.735420,78.549711,82.316189,84.818462,86.802858,86.509134,23.903047,28.415573,50.776539,62.443988,67.745795,92.628164,88.353994,86.290795,80.683702,72.846464
2796,Post-demographic dividend,207.346282,211.471705,212.211885,215.120862,213.243400,215.250636,209.725598,216.022470,NaN,198.965184,195.323606,180.453660,176.517804,181.440336,190.943268,191.091557,189.284668,184.200581,181.856715
2807,Pre-demographic dividend,16.107949,15.885314,16.373158,16.081856,16.915830,18.292140,21.948878,25.052458,24.162074,15.704203,11.882082,14.471803,14.332529,14.826927,9.930921,8.687435,6.115434,8.518785,11.147181
2818,Small states,86.797197,80.528816,75.097689,77.129065,74.802414,76.898629,96.010677,104.690764,105.274073,44.270651,40.690678,45.946152,49.314766,50.652653,72.860497,75.570144,69.850786,69.066138,50.994439
2829,South Asia,67.145039,69.178584,70.791399,71.680860,72.399485,70.998399,71.007518,71.283606,70.441591,46.804075,49.063958,51.052417,54.470750,53.546987,65.355823,59.340169,58.623254,57.282950,55.949974
2840,South Asia (IDA & IBRD),67.145039,69.178584,70.791399,71.680860,72.399485,70.998399,71.007518,71.283606,70.441591,46.804075,49.063958,51.052417,54.470750,53.546987,65.355823,59.340169,58.623254,57.282950,55.949974
2851,Sub-Saharan Africa,64.665692,67.661475,62.897520,62.045919,57.397823,55.636283,56.026908,58.364162,63.366678,68.886540,61.990202,70.942238,58.895023,67.887447,52.952219,65.449460,65.897975,69.910324,70.997458
2862,Sub-Saharan Africa (excluding high income),64.682474,67.674848,62.910982,62.063165,57.413581,55.652036,56.044776,58.382151,63.386104,68.825685,61.913636,70.863819,58.772960,67.792476,52.941586,65.438657,65.875555,69.870224,70.944755
2873,Sub-Saharan Africa (IDA & IBRD countries),64.665692,67.661475,62.897520,62.045919,57.397823,55.636283,56.026908,58.364162,63.366678,68.886540,61.990202,70.942238,58.895023,67.887447,52.952219,65.449460,65.897975,69.910324,70.997458
2884,Upper middle income,94.594054,96.544061,97.173965,103.775779,109.707623,120.379005,143.777614,158.745052,160.055594,76.326989,71.523538,74.853295,81.994604,86.310078,76.162954,78.848250,78.319210,77.255138,80.398536
2895,World,167.395987,166.039641,163.587804,165.103249,164.577759,168.878176,172.542844,181.092626,NaN,167.319540,162.036018,156.697127,155.189675,159.493536,153.167533,156.875508,157.798032,156.632908,157.797732

In [0]:
dom_credit.

In [0]:
pov_natl_rate = wdi[wdi['Series Name']=="Poverty (natl lines)"].drop(
    columns=['Series Name'])

In [0]:
pov_190 = wdi[wdi['Series Name']=="Poverty (1.90)"].drop(
    columns=['Series Name'])

In [0]:
hci = wdi[wdi['Series Name']=="HCI"].drop(
    columns=['Series Name'])

In [0]:
ag = wdi[wdi['Series Name']=="Agriculture pct of GDP"].drop(
    columns=['Series Name'])

In [0]:
gni = wdi[wdi['Series Name']=="GNI per capita"].drop(
    columns=['Series Name'])

In [0]:
fdi = wdi[wdi['Series Name']=="FDI"].drop(
    columns=['Series Name'])

In [0]:
electricity = wdi[wdi['Series Name']=="Access to electricity (% of population)"].drop(
    columns=['Series Name'])

# Missing data for 2017
electricity = electricity.drop(columns = [2017])

**Preliminary visualizations:**